# 1导入

In [2]:
import numpy as np

numpy的数据类型

In [5]:
array = np.array([1,2,3,4])

type(array)

numpy.ndarray

# 2创建ndarray

In [6]:
array1 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])  # 使用一个二维的list生成一个二维的ndarray
array2 = np.array([10, 11, 12, 13])   # 创建一个1维的ndarray

## 2.1常用属性

In [9]:
array1.shape,array2.shape

((3, 3), (4,))

In [12]:
array1.ndim

2

In [14]:
# 元素的数据类型
array1.dtype

dtype('int32')

In [15]:
array.size

4

## 2.2创建特殊类型的的ndarray

In [16]:
array = np.arange(10, 15, 0.5, dtype=np.float)
print(array) # [10.  10.5 11.  11.5 12.  12.5 13.  13.5 14.  14.5]

[10.  10.5 11.  11.5 12.  12.5 13.  13.5 14.  14.5]


In [17]:
array = np.logspace(0, 1, 5)  # [0, 1]，10^0, 10^0.25 .. 10^1
print(array)  # [ 1.   1.77827941  3.16227766  5.62341325 10.  ]

[ 1.          1.77827941  3.16227766  5.62341325 10.        ]


In [18]:
array = np.r_[0:2:0.5]  # 快速创建行向量
print(array)        # [0.  0.5 1.  1.5]
print(array.shape)  # (4,)

[0.  0.5 1.  1.5]
(4,)


In [22]:
array = np.c_[0:2:0.5]  # 快速创建列向量
print(array)
print(array.shape)


[[0. ]
 [0.5]
 [1. ]
 [1.5]]
(4, 1)


In [23]:
array1 = np.zeros(3, dtype=np.float)
array2 = np.zeros((2, 3), dtype=np.float)
print(array1)
print(array2)

[0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


In [24]:
array1 = np.ones(3, dtype=np.float)
array2 = np.ones((2, 3), dtype=np.float)
print(array1)
print(array2)

[1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [25]:
array = np.linspace(2, 10, 6)
print(array)
array = array.reshape(2, -1)  # -1为占位，numpy可以推测后面的值
print(array)

[ 2.   3.6  5.2  6.8  8.4 10. ]
[[ 2.   3.6  5.2]
 [ 6.8  8.4 10. ]]


In [26]:
array = np.eye(5) # 单位矩阵 # 等同于np.identity(5)
print(array)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# 3矩阵计算

In [27]:
array = np.arange(2, 5, 0.5, dtype=np.float).reshape(3, -1)
print(array)
print(2 + array)
print(array - 2)
print(array/2)
print(2*array)
print(np.log(array))
print(np.power(array, 2))
print(np.sqrt(array))

[[2.  2.5]
 [3.  3.5]
 [4.  4.5]]
[[4.  4.5]
 [5.  5.5]
 [6.  6.5]]
[[0.  0.5]
 [1.  1.5]
 [2.  2.5]]
[[1.   1.25]
 [1.5  1.75]
 [2.   2.25]]
[[4. 5.]
 [6. 7.]
 [8. 9.]]
[[0.69314718 0.91629073]
 [1.09861229 1.25276297]
 [1.38629436 1.5040774 ]]
[[ 4.    6.25]
 [ 9.   12.25]
 [16.   20.25]]
[[1.41421356 1.58113883]
 [1.73205081 1.87082869]
 [2.         2.12132034]]


In [28]:
# 转置
array = np.arange(2, 5, 0.5, dtype=np.float).reshape(3, -1)
print(array.T)
print(np.transpose(array))

[[2.  3.  4. ]
 [2.5 3.5 4.5]]
[[2.  3.  4. ]
 [2.5 3.5 4.5]]


In [30]:
#矩阵的数值运算
np.random.seed(1)   # 设置随机数种子，保证每次生成的随机数相同
array = 10*np.random.random((3, 2))
print(array)
print(array.sum())  # 整个矩阵各个元素的和
print(array.sum(axis=1))  # 各行的和
print(array.sum(axis=0))  # 各列的和
print(array.max()) # 整个矩阵中的最大值
print(array.max(axis=1))  # 各行的最大值
print(array.max(axis=0))  # 各列的最大值

[[4.17022005e+00 7.20324493e+00]
 [1.14374817e-03 3.02332573e+00]
 [1.46755891e+00 9.23385948e-01]]
16.788879311798276
[11.37346498  3.02446947  2.39094486]
[ 5.6389227  11.14995661]
7.203244934421581
[7.20324493 3.02332573 1.46755891]
[4.17022005 7.20324493]


In [31]:
array = np.arange(1, 13).reshape(3, -1)
print(array)
print(array.prod())      # 元素累乘
print(array.mean())      # 矩阵各元素平均值
print(np.median(array))  #  矩阵中值
print(array.std())       #  各元素标准差
print(array.var())       #  各元素方差
print(np.diff(array))    #  当前元素减去前面元素的差
print(np.cumsum(array))  #  每个元素变成当前元素＋前面所有元素的和

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
479001600
6.5
6.5
3.452052529534663
11.916666666666666
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[ 1  3  6 10 15 21 28 36 45 55 66 78]


In [32]:

array = np.linspace(1, 10, 9, dtype=np.float).reshape(3, -1)
print(array)
#根据条件修改矩阵数值。 如比 4 小的全部为 4，比 8 大的全部为 8，四舍五入(可指定精度)：
print(np.clip(array, 4, 8))
 # 对第一位小数点进行四舍五入，默认四舍五入到整数
print(array.round(decimals=1))

[[ 1.     2.125  3.25 ]
 [ 4.375  5.5    6.625]
 [ 7.75   8.875 10.   ]]
[[4.    4.    4.   ]
 [4.375 5.5   6.625]
 [7.75  8.    8.   ]]
[[ 1.   2.1  3.2]
 [ 4.4  5.5  6.6]
 [ 7.8  8.9 10. ]]


In [34]:
#矩阵求逆

a = np.arange(1, 10).reshape(3, 3)
print(a)
print(np.linalg.inv(a))  #linalg线性代数库

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


## 3.2 两个矩阵操作

In [36]:
#两个形状相同的矩阵对应元素操作，比较元素大小

array = np.arange(2, 5, 0.5, dtype=np.float).reshape(3, -1)
array1 = np.arange(3, 6, 0.5, dtype=np.float).reshape(3, -1)
print(array)
print(array1)
print(array1 + array)
print(array - array1)
print(array/array1)
print(array1*array)  # 等同于 np.multiply(array1, array)
print(np.log(array))
print(np.power(array, array1))
print(array > 2.5)
print(array > array1)

[[2.  2.5]
 [3.  3.5]
 [4.  4.5]]
[[3.  3.5]
 [4.  4.5]
 [5.  5.5]]
[[ 5.  6.]
 [ 7.  8.]
 [ 9. 10.]]
[[-1. -1.]
 [-1. -1.]
 [-1. -1.]]
[[0.66666667 0.71428571]
 [0.75       0.77777778]
 [0.8        0.81818182]]
[[ 6.    8.75]
 [12.   15.75]
 [20.   24.75]]
[[0.69314718 0.91629073]
 [1.09861229 1.25276297]
 [1.38629436 1.5040774 ]]
[[   8.           24.70529422]
 [  81.          280.7412308 ]
 [1024.         3914.43265521]]
[[False False]
 [ True  True]
 [ True  True]]
[[False False]
 [False False]
 [False False]]


In [39]:
#矩阵相乘 # 点乘

array1 = np.arange(2, 10).reshape(2, -1)
array2 = np.arange(4, 12).reshape(-1, 2)
# 方式1
print(array1.dot(array2))
# 方式2
print(np.dot(array1, array2))
# 方式3
print(array1 @ array2)

[[108 122]
 [220 250]]
[[108 122]
 [220 250]]
[[108 122]
 [220 250]]


# 4 切片和索引

##    4.1 获取指定值的索引

In [41]:
# 获取一个矩阵最大值、最小值以及非零索引
array = np.array([[-6, 6, 1],
                 [-2, 1, 7],
                 [0, 2, 0]])
print(np.argmin(array))   # 获取矩阵最小值索引
print(np.argmax(array))   # 获取矩阵最大值索引
print(np.argmin(array, axis=0)) # 获取矩阵每列的最小值索引
print(np.nonzero(array))  # 可以理解第1个array代表行，第2个代表列

0
5
[0 1 2]
(array([0, 0, 0, 1, 1, 1, 2], dtype=int64), array([0, 1, 2, 0, 1, 2, 1], dtype=int64))


## 4.2 获取矩阵块数据

In [42]:
#获取矩阵中具体的某个值，获取矩阵指定行，获取矩阵指定列，获取指定的行和列。

array = np.array([[-6, 6, 1],
                 [-2, 1, 7],
                 [0, 2, 0]])
print(array[1,2], array[1][2])  # 获取索引为1行2列的值
print(array[1], array[:][1])    # 获取索引为1的行,array[:][1]:所有行中的第1行
print(array[:, 1])              # 索引为1的列，返回为一个行向量（确定只有1列返回行）
print(array[:, 1:2])            # 索引为1的列，返回为一个列向量（:则是切片，保持原来的维度）

7 7
[-2  1  7] [-2  1  7]
[6 1 2]
[[6]
 [1]
 [2]]


In [43]:
# 数据迭代，迭代矩阵的行或列。

array = np.array([[-6, 6, 1],
                 [-2, 1, 7],
                 [0, 2, 0]])
# 行迭代
for row in array:
    print(row)
# 列迭代
for col in array.T:
    print(col)

[-6  6  1]
[-2  1  7]
[0 2 0]
[-6 -2  0]
[6 1 2]
[1 7 0]


In [44]:
# 将矩阵降低一维(内存降低一维)，对于二维矩阵来说，最后变成一个行向量

array = np.array([[-6, 6, 1],
                 [-2, 1, 7],
                 [0, 2, 0]])
print(array.flatten())
# [-6  6  1 -2  1  7  0  2  0]

[-6  6  1 -2  1  7  0  2  0]


## 4.3 使用 bool 索引进行切片

In [45]:
# 通过布尔类型选择数据， 布尔类型的矩阵也可以通过是矩阵的比较得到(ndarray > a， ndarray == ndarray 等)

a = np.arange(0, 100, 20)
mask = np.array([0, 0, 1, 0, -1], dtype=bool) # 0表示False，0之外的表示True
print(a)
print(mask)
print(a[mask])  # 通过布尔类型来选择数据

[ 0 20 40 60 80]
[False False  True False  True]
[40 80]


#  5 扩展与分解

## 5.1 矩阵合并

In [47]:
# 多个行向量合并，矩阵合并，

a = np.arange(1, 4)
b = np.arange(4, 7)
c = np.vstack((a, b, a, b))  # 垂直合并
print(c)
d = np.hstack((a, b, a, b))  # 水平合并，就是拼接
print(d)
c1 = np.vstack((a.T, b.T, a.T, b.T))

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
[1 2 3 4 5 6 1 2 3 4 5 6]


In [49]:
a = np.arange(1, 5).reshape(2, -1)
b = np.arange(5, 9).reshape(2, -1)
print(a)
print(b)
print(np.vstack((a,b)))  # 垂直合并
print(np.hstack((a,b)))  # 水平合并，就是拼接

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [56]:
# 行向量转为列向量(矩阵)
a = np.arange(1, 5)
print(a.reshape(1, -1))   # 错误方法
print(a[:, np.newaxis])   # 转换成列向量  
    # newaxis 插入新维度
print(a.T)
    # 补充： 对于行向量，使用转置方法返回还是行向量。

[[1 2 3 4]]
[[1]
 [2]
 [3]
 [4]]
[1 2 3 4]


In [55]:
# 列向量的合并

a = np.arange(1, 5)[:, np.newaxis]
b = np.arange(5, 9)[:, np.newaxis]
c = np.concatenate((a, b, a))  # 列向量的拼接，矩阵的拼接, axis参数默认为0，在垂直方向拼接（行的拼接）
print(c)
d = np.concatenate((a, b, a), axis=1) # 在水平方向拼接（列的拼接）
print(d)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [1]
 [2]
 [3]
 [4]]
[[1 5 1]
 [2 6 2]
 [3 7 3]
 [4 8 4]]


## 5.2 矩阵分解

In [58]:
# 将矩阵沿水平、垂直方向分解

a = np.arange(12).reshape(3, 4)
print(a)
# 均匀分开
print(np.split(a, 2, axis=1))  # 垂直方向（从上到下劈一刀）均匀（4/2=2）分成2份
print(np.split(a, 3, axis=0))  # 水平方向（从左到右劈三刀）均匀（3/1=3）分成3份

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


In [60]:
# 将列向量转换为行向量

array = np.arange(12)[:, np.newaxis]
print(array.squeeze()) # 降维度

[ 0  1  2  3  4  5  6  7  8  9 10 11]


# 6 随机模块

In [61]:
#设置随机数种子，保持每次得到的数据一致

np.random.seed(10)

In [62]:
#从 0-10 中随机选出 5 个随机数行向量

print(np.random.choice(11, size=5))  # 选出的元素可重复，但不可是

[9 4 0 1 9]


In [63]:
# 随机生成指定维度，满足 0-1 均匀分布的矩阵(当 rand()中无参数，则返回一个标量的随机数值)

print(np.random.rand(3, 2)) # 返回服从[0, 1)均匀分布的随机样本值

[[0.58332174 0.02517173]
 [0.70920801 0.26556613]
 [0.26360285 0.15037787]]


In [64]:
#返回区间在[0, a)上指定维度的整数矩阵

print(np.random.randint(15, size=(2,3)))

[[ 3  0  4]
 [11  6  8]]


In [65]:
#返回区间在自定义区间上指定维度的整数矩阵

print(np.random.randint(10, 15, size=(2,3)))

[[13 12 11]
 [10 14 11]]


In [66]:
#返回服从高斯分布中均值为 [公式]，方差 [公式] 的指定维数矩阵

mu = 0  #  均值
sigma = 1  # 方差
print(np.random.normal(mu, sigma, (2, 5)))

[[ 0.22863013  0.44513761 -1.13660221  0.13513688  1.484537  ]
 [-1.07980489 -1.97772828 -1.7433723   0.26607016  2.38496733]]


In [68]:
#对一数据，随机打散 ()

array = np.arange(10).reshape(2,5)
print(array)
np.random.shuffle(array) # 随机洗牌
print(array)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


# 7 其它操作

In [69]:
#在使用时需要注意，数据是否共有内存，避免修改一地方的值，另外一个地方的值也随之变化。

a = np.arange(5)
b = a
c = b
d = c # a,b,c,d指向同一数据地址
print(d is a, c is a, b is a) # True True True
d[0] = 100
print(a)        # d改动，a随着变化
e = a.copy()    # 拷贝一份a给e，a,e不共享内存
print(e is a)
e[0] = 20
print(e, a)

True True True
[100   1   2   3   4]
False
[20  1  2  3  4] [100   1   2   3   4]


In [70]:
# 矩阵元素排序

array = np.array([[-6, 6, 1],
                 [-2, 1, 7],
                 [0, 2, 0]])
 # 默认对每行的数据从左至右，从小到大排序, 参数axis默认为0
print(np.sort(array))
print(np.sort(array, axis=1)) # 对列进行排序，从上到下，从小到大排序

[[-6  1  6]
 [-2  1  7]
 [ 0  0  2]]
[[-6  1  6]
 [-2  1  7]
 [ 0  0  2]]
