# numpy.array 

In [26]:
import numpy as np

In [27]:
list_1= list([1.0,2,3])
list_2= list([4,5,6])

In [28]:
array_1=np.array([list_1,list_2])

In [29]:
array_1

array([[1., 2., 3.],
       [4., 5., 6.]])

In [30]:
array_1.dtype

dtype('float64')

In [31]:
array_1.shape# 2x3的矩阵

(2, 3)

In [32]:
array_1.size

6

In [35]:
np.arange(1, 9)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [36]:
#[1,9)以2为间隔的顺序序列
np.arange(1, 9,2)

array([1, 3, 5, 7])

In [44]:
np.zeros([2,4])#2x4零矩阵

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [45]:
np.eye(3)#单位矩阵

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [46]:
np.eye(3).dtype

dtype('float64')

In [48]:
a = np.arange(1,10)

In [49]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
a[1]

2

In [51]:
#一维数组切片
a[1:5]

array([2, 3, 4, 5])

In [52]:
a2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [53]:
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
a2[1,0]

4

In [55]:
#二维数组切片
a2[:2,1:]

array([[2, 3],
       [5, 6]])