## 随机数

In [2]:
import numpy as np

In [3]:
#正态分布
np.random.randn(5)

array([ 0.86333682, -1.13553497, -0.27344476, -0.33334816, -1.95290475])

In [4]:
#[0,10)随机数
np.random.randint(10)

1

In [5]:
np.random.randint(10,size=(4,5))

array([[5, 5, 4, 8, 7],
       [5, 9, 2, 2, 1],
       [6, 2, 3, 6, 5],
       [4, 4, 9, 6, 4]])

In [6]:
np.random.randint(10,size=20)

array([8, 2, 0, 3, 8, 0, 1, 7, 7, 3, 0, 9, 1, 8, 3, 7, 6, 3, 6, 9])

In [7]:
np.random.randint(10,size=20).reshape(4,5)

array([[9, 6, 0, 8, 5],
       [6, 2, 6, 4, 1],
       [3, 8, 4, 3, 5],
       [2, 1, 3, 7, 9]])

## 数组运算

In [8]:
a = np.random.randint(10,size=4).reshape(2,2)
b = np.random.randint(10,size=4).reshape(2,2)

In [9]:
a

array([[6, 9],
       [0, 6]])

In [10]:
b

array([[8, 9],
       [9, 0]])

In [11]:
a + b

array([[14, 18],
       [ 9,  6]])

In [12]:
a - b

array([[-2,  0],
       [-9,  6]])

In [13]:
# 数组对应元素相乘（区别于矩阵乘法）
a * b

array([[48, 81],
       [ 0,  0]])

In [14]:
# 除法对应元素相除，但分母不可为0
a / b

D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([[0.75, 1.  ],
       [0.  ,  inf]])

## 矩阵运算

In [15]:
np.mat([[1,2,3],[4,5,6]])

matrix([[1, 2, 3],
        [4, 5, 6]])

In [16]:
#array转为matrix
A = np.mat(a)
B = np.mat(b)

In [17]:
A

matrix([[6, 9],
        [0, 6]])

In [18]:
B

matrix([[8, 9],
        [9, 0]])

In [19]:
#矩阵的加法减法同数组，对应元素运算
#矩阵乘法
a * b

array([[48, 81],
       [ 0,  0]])

## Array常用函数

In [20]:
a = np.random.randint(10,size=20).reshape(4,5)

In [21]:
a

array([[3, 6, 6, 0, 3],
       [5, 6, 3, 5, 6],
       [8, 4, 0, 2, 4],
       [0, 1, 6, 1, 6]])

In [70]:
np.unique(a)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [74]:
# 列和
sum(a)

array([10, 23, 17, 11, 14])

In [97]:
# 第0列和
sum(a[:,0])

10

In [98]:
#第1行和
sum(a[1])

18

In [99]:
a.max()

8

In [100]:
np.sum(a)

75

In [101]:
# 0行最大值
max(a[0])

4

In [102]:
# 0列最大值
max(a[:,0])

4